language: node_js
node_js:
  - "8.1.2"
env:
  - CXX=g++-4.8
    NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
script:
  - npm test