sudo: required
language: node_js
node_js:
  - "8.1.2"
env:
  - CXX=g++-4.8
    NODE_ENV=test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install tar@3.1.5
  - sudo $(which node) scripts/download-libtensorflow.js
install:
  - npm install
script:
  - sudo $(which npm) test
cache:
  directories:
    - "node_modules"
