language: node_js
node_js:
  - "8.1.2"
env:
  - CXX=g++-4.8
    NODE_ENV=test
    LIBRARY_PATH=$PWD/tensorflow/lib:$LIBRARY_PATH
    LD_LIBRARY_PATH=$PWD/tensorflow/lib:/tmp/libc6_2.17/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  # install glibc 2.17
  - cd /tmp
  - wget http://launchpadlibrarian.net/137699828/libc6_2.17-0ubuntu5_amd64.deb
  - wget http://launchpadlibrarian.net/137699829/libc6-dev_2.17-0ubuntu5_amd64.deb
  - mkdir libc6_2.17 && cd libc6_2.17
  - ar p libc6_2.17-0ubuntu5_amd64.deb data.tar.gz | tar zx
  - ar p libc6-dev_2.17-0ubuntu5_amd64.deb data.tar.gz | tar zx
  - cd ../
  # install tensorflow lib
  - npm install tar@3.1.5
  - node scripts/download-libtensorflow.js
install:
  - npm install
script:
  - echo $LD_LIBRARY_PATH
  - node test/test_op_array.js
cache:
  directories:
    - "node_modules"
