dist: trusty
sudo: false
language: node_js
node_js:
  - "8.1.2"
env:
  - CXX=g++-4.8
    NODE_ENV=test
    LIBRARY_PATH=$PWD/tensorflow/lib:$LIBRARY_PATH
    LD_LIBRARY_PATH=$PWD/tensorflow/lib:$LD_LIBRARY_PATH
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  # install tensorflow lib
  - npm install tar@3.1.5
  - node scripts/download-libtensorflow.js
install:
  - npm install
script:
  - echo $LD_LIBRARY_PATH
  - npm test
cache:
  directories:
    - "node_modules"
